### ISSUE TITLE
Calls to int_asbuffer are failing

### ISSUE THREAD

**Issue by jkrasting** [raphaeldussin/ESMPy3#3]
Many thanks for this port.

The developers of numpy appear to have done away with multiarray.int_asbuffer functionality, which is used in ESMPy.

https://github.com/numpy/numpy/blob/master/doc/Py3K.rst.txt

This is causing the tests and the package to fail now with my build of Python v3.5 and Numpy 1.12.0.  Do you have any suggestions?

**Comment by raphaeldussin** [comment]
This port is incomplete. Ryan (from ESMF) finished the job and it is now part of ESMF 7.1.0 beta.
Check if the master has the python3 version here : 

https://sourceforge.net/p/esmf/esmf/ci/master/tree/

or drop a line to Ryan.

**Comment by jkrasting** [comment]
Great.  Many thanks!


-----
Dr. John Krasting, Physical Scientist
NOAA/Geophysical Fluid Dynamics Laboratory
Biogeochemistry, Ecosystems, and Climate Group
201 Forrestal Road, Princeton, NJ 08540
P. (609) 452-5359   |   F. (609) 987-5063
